In [2]:
import numpy as np 

In [3]:
# Create array , Matrix

a = np.array([1,2,3,4])

In [4]:
# Vector
a

array([1, 2, 3, 4])

In [5]:
# Matrix
b = np.array([[1,2], [3,4]])
b

array([[1, 2],
       [3, 4]])

In [6]:
# Shape
print(b.shape,'\n', a.shape)

(2, 2) 
 (4,)


In [7]:
# reshape
c = a.reshape((4,1))
c.shape

(4, 1)

In [8]:
# d = a.reshape((2,-1,1))با منفی یک عددش میفهمه حودش
d = a.reshape((2,2,1))
d.shape

(2, 2, 1)

In [9]:
# Concatenate

a = np.array([1,2,3])
b = np.array([4,5])

c = np.concatenate((a,b))
c

array([1, 2, 3, 4, 5])

In [10]:
a = np.array([1,2,3])
b = np.array([4,5,6])

c =  a * b 
c

array([ 4, 10, 18])

In [11]:
a = np.array([1,2,3])
d = np.array([10])
# c = a * d
# c = a * 10
c = a + d
c


array([11, 12, 13])

In [12]:
# slice یا انتخاب بخشی از لیست >> list_name = [start:end:step]

a = np.array([1,2,3,4,5,6,7,8,9])
# b = a[2:7]
# b = a[2:-2]
# b = a[2:7:2]
# b


In [13]:
# if in []
a = np.array([1,2,3,4,5,6,7,8,9])
b = a[a>3]
# b

result =[]
for i in a:
    if i > 3:
        result.append(i)
# result

print(b, '\n', result)

[4 5 6 7 8 9] 
 [np.int64(4), np.int64(5), np.int64(6), np.int64(7), np.int64(8), np.int64(9)]


In [14]:
sum_a = np.sum(a)
sum_a

np.int64(45)

In [15]:
max_a= np.max(a)
max_a


np.int64(9)

In [16]:
min_a = np.min(a)
min_a

np.int64(1)

In [17]:
a = np.array([4,2,3,9,1,6,8,5,7])
sort_a = np.sort(a)
sort_a

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [18]:
a = np.random.randint(-100,100,(3,4))
a

array([[ 53, -92, -33, -96],
       [-89,  34, -88,  77],
       [-94, -24, -82,  85]], dtype=int32)

In [ ]:
a = np.array([1,2,3])
b = np.array([4,5,6])
c = np.vstack((b,a)) # به صورت سطر انها را روی یکدیگر قرار میدهد
c = np.hstack((a,b)) # در این دستور ما ارایه هارا به صورت ستونی به هم مچیسبانیم
c

array([1, 2, 3, 4, 5, 6])

In [20]:
# normalize
a = np.array([1,2,3])
a

array([1, 2, 3])

In [21]:
"""
میانگین ارایه را اول حساب میکنیم
"""
mean_a= np.mean(a)
mean_a

np.float64(2.0)

In [22]:
"""
انحراف از معیار ارایه خود را محاسبه میکنیم
"""
std_a = np.std(a)
std_a

np.float64(0.816496580927726)

In [23]:
"""
برای بدست اوردن نرمالایز ارایه ابتدا
ارایه رو منحای مقدار میانگینش میکنیم و کلشو تقسیم بر انحراف از معیارش
 که بتونیم نرمالایز شده ارایه رو بدست بیاریم
"""
norm_a = (a - mean_a)/ std_a
norm_a

array([-1.22474487,  0.        ,  1.22474487])

In [24]:
# np.mean(norm_a)
np.std(norm_a)

np.float64(0.9999999999999999)

In [25]:
c= np.transpose(a)
c


array([1, 2, 3])